
trigger:
- releases/*

pool:
  vmImage: windows-latest

steps:
- script: echo Execute Pipeline
  displayName: 'Execute Pipeline'
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/wesley-trust/GraphAPI.git'
    workingDirectory: '$(System.ArtifactsDirectory)'
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/wesley-trust/ToolKit.git'
    workingDirectory: '$(System.ArtifactsDirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      . $(System.ArtifactsDirectory)\GraphAPI\Public\AzureAD\ConditionalAccess\Import-WTCAPolicy.ps1

            Import-WTCAPolicy `
              -TenantDomain $(TenantDomain) `
              -ClientID ${env:CLIENTID} `
              -ClientSecret ${env:CLIENTSECRET} `
              -Path $(Build.Repository.LocalPath)\AzureAD\ConditionalAccess `
              -UpdateExistingPolicies `
              -RemoveExistingPolicies `
              -Force
    pwsh: true
    workingDirectory: '$(System.ArtifactsDirectory)'
  env:
    CLIENTID: $(ClientID)
    CLIENTSECRET: $(ClientSecret)

- task: CmdLine@2
  inputs:
    script: 'git config user.email AzurePipeline@wesleytrust.com'

- task: CmdLine@2
  inputs:
    script: 'git config user.name AzurePipeline'

- task: CmdLine@2
  inputs:
    script: 'git commit -a -m "Commit configuration changes post deployment [skip ci]"'

- task: CmdLine@2
  inputs:
    script: 'git push https://%GITHUBPAT%@github.com/wesley-trust/GraphAPIConfig.git HEAD:main'
  env:
    GITHUBPAT: $(GitHubPAT)