# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Execute Pipeline
  displayName: 'Execute Pipeline'
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'wesley-trust-PAT-Full'
    userRepository: 'wesley-trust/GraphAPI'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'wesley-trust-PAT-Full'
    userRepository: 'wesley-trust/ToolKit'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/*.zip'
    destinationFolder: '$(System.ArtifactsDirectory)/GitHub'
    cleanDestinationFolder: true
    overwriteExistingFiles: false
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'ls $(System.ArtifactsDirectory)'
    pwsh: true
    workingDirectory: '$(System.ArtifactsDirectory)/GitHub'





