# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Execute Pipeline
  displayName: 'Execute Pipeline'

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'wesley-trust-PAT-Full'
    userRepository: 'wesley-trust/ToolKit'
    defaultVersionType: 'specificVersion'
    version: '39287989'
    itemPattern: '*.zip'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/*.zip'
    destinationFolder: '$(System.ArtifactsDirectory)/GitHub'
    cleanDestinationFolder: true
    overwriteExistingFiles: false

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      . $(System.ArtifactsDirectory)/GitHub/GraphAPI/Public/AzureAD/ConditionalAccess/Import-WTCAPolicy.ps1
            
            Import-WTCAPolicy `
              -TenantDomain $(TenantDomain) `
              -ClientID $(ClientID) `
              -ClientSecret $(ClientSecret) `
              -Path $(Agent.BuildDirectory)/AzureAD/ConditionalAccess `
              -UpdateExistingPolicies `
              -RemoveExistingPolicies `
              -Force
    pwsh: true
    workingDirectory: '$(System.ArtifactsDirectory)/GitHub'

