trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Execute Pipeline
  displayName: 'Execute Pipeline'
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/wesley-trust/GraphAPI.git'
    workingDirectory: '$(System.ArtifactsDirectory)'
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/wesley-trust/ToolKit.git'
    workingDirectory: '$(System.ArtifactsDirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      . $(System.ArtifactsDirectory)\GraphAPI\Public\AzureAD\ConditionalAccess\Invoke-WTCAPolicyImport.ps1
            Invoke-WTCAPolicyImport `
              -TenantDomain $(TenantDomain) `
              -ClientID ${env:CLIENTID} `
              -ClientSecret ${env:CLIENTSECRET} `
              -Path $(Build.Repository.LocalPath)\AzureAD\ConditionalAccess `
              -UpdateExistingPolicies `
              -RemoveExistingPolicies `
              -Force
    pwsh: true
    workingDirectory: '$(System.ArtifactsDirectory)'
  env:
    CLIENTID: $(ClientID)
    CLIENTSECRET: $(ClientSecret)
    GITHUBPAT: $(GitHubPAT)