trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Validate
  jobs:
  - job: Import
    continueOnError: false
    steps:
    - task: CmdLine@2
      name: CloneGraphAPI
      inputs:
        script: 'git clone https://github.com/wesley-trust/GraphAPI.git'
        workingDirectory: '$(System.ArtifactsDirectory)'
    - task: CmdLine@2
      name: CloneToolKit
      inputs:
        script: 'git clone https://github.com/wesley-trust/ToolKit.git'
        workingDirectory: '$(System.ArtifactsDirectory)'
    - task: PowerShell@2
      name: InvokeWTValidateCAPolicy
      inputs:
        targetType: 'inline'
        script: |
          $ValidateCAPolicies = @{Name = "Value"}

          $ValidateCAPolicies = @{Name = "Value"} | ConvertTo-Json
          $ValidateCAPolicies = [System.Text.Encoding]::Unicode.GetBytes($ValidateCAPolicies)
          $EncodeValidateCAPolicies =[Convert]::ToBase64String($ValidateCAPolicies)

          Write-Host "##vso[task.setvariable variable=ValidateObject;isOutput=true]$EncodeValidateCAPolicies"
        pwsh: true
        workingDirectory: '$(System.ArtifactsDirectory)'
- stage: Plan
  dependsOn: Validate
  variables:
    ValidateCAPolicies: $[ stageDependencies.Validate.Import.outputs['InvokeWTValidateCAPolicy.ValidateObject'] ]
  jobs:
  - job: Evaluate
    steps:
    - task: PowerShell@2
      name: InvokeWTValidateCAPolicy
      inputs:
        targetType: 'inline'
        script: |
          $DecodeValidateCAPolicies = $(ValidateCAPolicies)
          $DecodeValidateCAPolicies = [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($DecodeValidateCAPolicies))
          $DecodeValidateCAPolicies = $DecodeValidateCAPolicies | ConvertFrom-JSON
          $DecodeValidateCAPolicies
        pwsh: true
        workingDirectory: '$(System.ArtifactsDirectory)'