trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Validate
  jobs:
  - job: Import
    steps:
    - task: PowerShell@2
      name: InvokeWTValidateCAPolicy
      inputs:
        targetType: 'inline'
        script: |
          $ValidateCAPolicies = "Validate Object"
          echo "##vso[task.setvariable variable=ValidateObject;isOutput=true]$ValidateCAPolicies"
        pwsh: true
        workingDirectory: '$(System.ArtifactsDirectory)'
- stage: Plan
  dependsOn: Validate
  variables:
    ValidateCAPolicies: $[ stageDependencies.Validate.Import.outputs['InvokeWTValidateCAPolicy.ValidateObject'] ]
  jobs:
  - job: Evaluate
    steps:
    - script: echo $(ValidateCAPolicies)