trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: 'Validate'
  jobs:
  - job: 'Import'
    continueOnError: false
    steps:
    - task: PowerShell@2
      name: 'InvokeWTValidateCAPolicy'
      inputs:
        targetType: 'inline'
        script: |
          $ValidateCAPolicies = "Variable from Stage Validate"
          echo $ValidateCAPolicies
          echo "##vso[task.setvariable variable=ValidateObject;isOutput=true;]$ValidateCAPolicies"

        pwsh: true
        workingDirectory: '$(System.ArtifactsDirectory)'
- stage: 'Plan'
  variables:
    ValidateCAPolicies: $[ stageDependencies.validate.import.outputs['InvokeWTValidateCAPolicy.ValidateObject'] ]
  jobs:
  - deployment: 'Evaluate'
    continueOnError: false
    environment: 'staging'
    strategy:
     runOnce:
       deploy:
        steps:
          - task: PowerShell@2
            name: 'InvokeWTPlanCAPolicy'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host ${env:VALIDATECAPOLICIES}
                Write-Host $(ValidateCAPolicies)

              pwsh: true
              workingDirectory: '$(System.ArtifactsDirectory)'
            env:
              CLIENTID: $(ClientID)
              CLIENTSECRET: $(ClientSecret)
              VALIDATECAPOLICIES: $(ValidateCAPolicies)